DROP TABLE IF EXISTS students_courses;
DROP  TABLE IF EXISTS groups CASCADE;
DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS courses;

CREATE TABLE groups(
                       group_id  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                       group_name VARCHAR(10) NOT NULL
);

CREATE TABLE students(
                       student_id int GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY NOT NULL,
                       group_id int REFERENCES groups(group_id),
                       first_name VARCHAR(20) NOT NULL,
                       last_name VARCHAR(50) NOT NULL
);

CREATE TABLE courses(
                       course_id int GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY NOT NULL,
                       course_name VARCHAR(50) NOT NULL,
                       course_description VARCHAR(255) NOT NULL
);

CREATE TABLE students_courses (
                                  student_id int REFERENCES students (student_id) ON UPDATE CASCADE ON DELETE CASCADE,
                                  course_id int REFERENCES courses (course_id) ON UPDATE CASCADE ON DELETE CASCADE,
                                  PRIMARY KEY (student_id, course_id)
);





